#!/usr/bin/env bash
# Sync the prefix glossary from the skill's template into README.md, between the
# glossary:begin/end markers. The template's placeholders are the repo-specific
# parts an install fills in; the README shows them resolved to the generic
# wording, so a reader sees the table as it will land.
set -euo pipefail
cd "$(dirname "$0")"

python3 - <<'PY'
import pathlib, re, unicodedata

TEMPLATE = pathlib.Path("plugins/emotive/skills/emotive-setup/template.md")
README = pathlib.Path("README.md")
BEGIN = "<!-- glossary:begin (generated by ./build.sh — do not edit) -->"
END = "<!-- glossary:end -->"

GENERIC = {
    "<main branch>": "main",
    "<gated / tested>": "gated",
    "<the things this repo waits on>": "a decision, a credential, a click",
    "<the repo can only run one of>": "only one session can use at a time",
    "<the live resource every session shares>": "a live resource every session shares",
    "<the repo's own learnings files>": "`AGENTS.md`, `README.md` or the skills",
}

def width(s):
    # An emoji occupies two columns; a variation selector none — but it also
    # promotes the character it follows to emoji presentation, and so to two.
    def w(i, ch):
        if ch == "\ufe0f":
            return 0
        wide = (ord(ch) >= 0x1F300 or unicodedata.east_asian_width(ch) in "WF"
                or s[i + 1:i + 2] == "\ufe0f")
        return 2 if wide else 1
    return sum(w(i, ch) for i, ch in enumerate(s))

lines = TEMPLATE.read_text().split("\n")
start = next(i for i, l in enumerate(lines) if l.startswith("| Prefix"))
end = next(i for i in range(start, len(lines)) if not lines[i].startswith("|"))
rows = [[c.strip() for c in l.split("|")[1:-1]] for l in lines[start:end]]
head, rows = rows[0], rows[2:]
for row in rows:
    for i, cell in enumerate(row):
        for k, v in GENERIC.items():
            row[i] = row[i].replace(k, v)
# The template code-formats the prefix to keep its trailing space visible, which
# is what a session setting one needs; the README shows the bare emoji instead.
for row in rows:
    row[0] = row[0].strip("`").strip()
leftover = [c for r in rows for c in r if re.search(r"<[^>]+>", c)]
if leftover:
    raise SystemExit(f"build.sh: unresolved placeholder in the glossary: {leftover[0]}")

cols = range(len(head))
w = [max([width(head[c])] + [width(r[c]) for r in rows]) for c in cols]
pad = lambda s, n: s + " " * (n - width(s))
table = "\n".join(
    ["| " + " | ".join(pad(head[c], w[c]) for c in cols) + " |",
     "| " + " | ".join("-" * w[c] for c in cols) + " |"]
    + ["| " + " | ".join(pad(r[c], w[c]) for c in cols) + " |" for r in rows]
)

# The interactive skill asks in three groups of four. Every prefix in the
# glossary must appear in exactly one of them, or a stage becomes unpickable.
INTERACTIVE = pathlib.Path("plugins/emotive/skills/emotive-setup-interactive/SKILL.md")
ilines = INTERACTIVE.read_text().split("\n")
istart = next(i for i, l in enumerate(ilines) if l.startswith("| Question"))
iend = next(i for i in range(istart, len(ilines)) if not ilines[i].startswith("|"))
asked = [m.strip() for l in ilines[istart + 2:iend] for m in re.findall(r"`([^`]+)`", l.split("|")[2])]
listed = [re.search(r"`([^`]+)`", r[0]).group(1).strip() for r in rows]
if sorted(asked) != sorted(listed):
    missing = [p for p in listed if p not in asked]
    extra = [p for p in asked if p not in listed]
    raise SystemExit(f"build.sh: the interactive skill's groups do not cover the glossary: missing {missing}, extra {extra}")

readme = README.read_text()
for marker in (BEGIN, END):
    if marker not in readme:
        raise SystemExit(f"build.sh: marker missing from README.md: {marker}")
head, rest = readme.split(BEGIN, 1)
_, tail = rest.split(END, 1)
README.write_text(f"{head}{BEGIN}\n\n{table}\n\n{END}{tail}")
print(f"build.sh: injected the glossary into README.md; {len(asked)} prefixes asked in {iend - istart - 2} groups")
PY
