#!/usr/bin/env bash
# Normalize the prefix glossary in the injected context file, then copy it into
# README.md between the glossary:begin/end markers. An emoji is two columns wide
# and a variation selector is zero, so the table is padded by display width
# rather than by character count — which is why it is generated and not typed.
set -euo pipefail
cd "$(dirname "$0")"

python3 - <<'PY'
import pathlib, re, unicodedata

CONTEXT = pathlib.Path("plugins/emotive/context/session-titles.md")
README = pathlib.Path("README.md")
BEGIN = "<!-- glossary:begin (generated by ./build.sh — do not edit) -->"
END = "<!-- glossary:end -->"

def width(s):
    # An emoji occupies two columns; a variation selector none — but it also
    # promotes the character it follows to emoji presentation, and so to two.
    def w(i, ch):
        if ch == "️":
            return 0
        wide = (ord(ch) >= 0x1F300 or unicodedata.east_asian_width(ch) in "WF"
                or s[i + 1:i + 2] == "️")
        return 2 if wide else 1
    return sum(w(i, ch) for i, ch in enumerate(s))

def table(head, rows):
    cols = range(len(head))
    w = [max([width(head[c])] + [width(r[c]) for r in rows]) for c in cols]
    pad = lambda s, n: s + " " * (n - width(s))
    return "\n".join(
        ["| " + " | ".join(pad(head[c], w[c]) for c in cols) + " |",
         "| " + " | ".join("-" * w[c] for c in cols) + " |"]
        + ["| " + " | ".join(pad(r[c], w[c]) for c in cols) + " |" for r in rows]
    )

lines = CONTEXT.read_text().split("\n")
start = next(i for i, l in enumerate(lines) if l.startswith("| Prefix"))
end = next(i for i in range(start, len(lines)) if not lines[i].startswith("|"))
rows = [[c.strip() for c in l.split("|")[1:-1]] for l in lines[start:end]]
head, rows = rows[0], rows[2:]

# The injected copy ships as-is, so a placeholder in it would reach every
# session unresolved. The tailored wording belongs in template.md.
leftover = [c for r in rows for c in r if re.search(r"<[^>]+>", c)]
if leftover:
    raise SystemExit(f"build.sh: placeholder in the injected glossary: {leftover[0]}")

# Pad the source table too, so the file that actually ships is the one that is
# correct — nothing here has to be padded by hand.
CONTEXT.write_text("\n".join(lines[:start] + table(head, rows).split("\n") + lines[end:]))

# The injected copy code-formats the prefix to keep its trailing space visible,
# which is what a session setting one needs; the README shows the bare emoji.
# Different cell widths, so the two tables are padded separately.
bare = [[r[0].strip("`").strip()] + r[1:] for r in rows]

readme = README.read_text()
for marker in (BEGIN, END):
    if marker not in readme:
        raise SystemExit(f"build.sh: marker missing from README.md: {marker}")
pre, rest = readme.split(BEGIN, 1)
_, tail = rest.split(END, 1)
README.write_text(f"{pre}{BEGIN}\n\n{table(head, bare)}\n\n{END}{tail}")
print("build.sh: normalized the glossary and injected it into README.md")
PY
